import board

DEBUG = True

BRIGHTNESS_VARIANCE = 0.09
MIN_BRIGHTNESS = 0.1
MAX_BRIGHTNESS = 1
STARTING_BRIGHTNESS = (MIN_BRIGHTNESS + MAX_BRIGHTNESS) / 2

NUM_PIXELS = 24
PIXEL_PIN = board.D1

if DEBUG:
    BRIGHTNESS_VARIANCE = 0.01
    MIN_BRIGHTNESS = 0.05
    MAX_BRIGHTNESS = 0.3
